services:
  mysql:
    image: mysql:8.0
    container_name: fichme-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root_fichme_2026
      MYSQL_DATABASE: fichme
      MYSQL_USER: fichme_user
      MYSQL_PASSWORD: fichme_password_2026

    ports:
      - "3307:3306"

    volumes:
      - fichme_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "fichme_user",
          "-pfichme_password_2026"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  fichme_mysql_data: